language: java

jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_script:
 - export PG_PASSWORD=12345
 - psql -c "CREATE USER spring_services WITH PASSWORD '12345';" -U postgres
 - psql -c "ALTER USER spring_services  WITH SUPERUSER;" -U postgres
 - psql -c 'CREATE DATABASE spring_services OWNER spring_services;' -U postgres
 - psql -c 'GRANT ALL PRIVILEGES ON DATABASE spring_services to spring_services;' -U postgres
 - psql -d spring_services < src/main/resources/spring_services.backup -U spring_services

services:
 - postgresql

addons:
 postgresql: '9.4'
