language: java

jdk:
  - oraclejdk8

before_script:
     - psql -c "CREATE USER spring_services WITH PASSWORD '12345';" -U postgres
     - psql -c 'CREATE DATABASE spring_services OWNER spring_services;' -U postgres
     - psql -d spring_services -U spring_services < src/main/resources/_schema.sql
     - psql -d spring_services -U spring_services < src/main/resources/_data.sql
services:
 - postgresql

addons:
 postgresql: '9.4'
