language: java

jdk:
  - oraclejdk8

before_script:
     - psql -c "CREATE USER spring_services WITH PASSWORD '12345';" -U postgres
     - psql -c 'CREATE DATABASE spring_services OWNER spring_services;' -U postgres

services:
 - postgresql

addons:
 postgresql: '9.4'
